name: CI/CD

on:
  push:
    branches:
      - 'main'

env:
  path: /var/www/nikolab131.xyz
  tempPath: /var/tmp/nikolab131.xyz

jobs:
  build:
    name: 'Build'
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy
        run: |
          mkdir -p ${{env.path}}
          cp -r dist/* ${{env.tempPath}}

  deploy:
    needs: build
    name: 'Deploy'
    runs-on: self-hosted

    steps:
      - name: Save
        run: |
          mkdir -p ${{env.path}}
          cp -r ${{env.tempPath}}/* ${{env.path}}
